title: My New Website

description: >
  My New Website for SCHH Website Class

author:
  name: Mark
  email: Markpederson100@yahoo.com

nav_pages:
  - about.md
  - contact.md

max-width: 800px

show_excerpts: true
show_rss_feed: true
show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

content_selector: div.post-content,div.home
